apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"autoscaling/v2","kind":"HorizontalPodAutoscaler","metadata":{"annotations":{},"labels":{"app.kubernetes.io/part-of":"onlinejudge-platform","delivery.onlinejudge.io/owner-issue":"319"},"name":"assessment-api","namespace":"onlinejudge-platform"},"spec":{"behavior":{"scaleDown":{"stabilizationWindowSeconds":300}},"maxReplicas":3,"metrics":[{"resource":{"name":"cpu","target":{"averageUtilization":60,"type":"Utilization"}},"type":"Resource"}],"minReplicas":1,"scaleTargetRef":{"apiVersion":"apps/v1","kind":"Deployment","name":"assessment-api"}}}
  creationTimestamp: "2026-09-02T05:43:56Z"
  generation: 1
  labels:
    app.kubernetes.io/part-of: onlinejudge-platform
    delivery.onlinejudge.io/owner-issue: "319"
  name: assessment-api
  namespace: onlinejudge-platform
  resourceVersion: "38784"
  uid: 85ae058c-3133-440f-9f00-068c6f70a699
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Pods
        value: 4
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 0
  maxReplicas: 3
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 60
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: assessment-api
status:
  conditions:
  - lastTransitionTime: "2026-09-02T10:46:34Z"
    message: the HPA controller was able to update the target scale to 1
    reason: SucceededRescale
    status: "True"
    type: AbleToScale
  - lastTransitionTime: "2026-09-02T05:44:26Z"
    message: the HPA was able to successfully calculate a replica count from cpu resource
      utilization (percentage of request)
    reason: ValidMetricFound
    status: "True"
    type: ScalingActive
  - lastTransitionTime: "2026-09-02T12:12:56Z"
    message: the desired count is within the acceptable range
    reason: DesiredWithinRange
    status: "False"
    type: ScalingLimited
  - lastTransitionTime: "2026-09-02T06:04:27Z"
    message: the HPA controller did not scale the workload to zero
    reason: NotScaledToZero
    status: "False"
    type: ScaledToZero
  currentMetrics:
  - resource:
      current:
        averageUtilization: 0
        averageValue: 2m
      name: cpu
    type: Resource
  currentReplicas: 2
  desiredReplicas: 1
  lastScaleTime: "2026-09-02T12:23:57Z"
  observedGeneration: 1
