package com.onlinejudge.auth;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.assertj.core.api.Assertions.assertThat;

class AuthMigrationScriptTest {
    @Test
    void authMigrationUsesMysqlCompatibleIdentityAndTimestampSyntax() throws Exception {
        String migration = Files.readString(Path.of("../database/migrations/DB-AUTH-01-auth-user-session.sql"));

        assertThat(migration).contains("AUTO_INCREMENT");
        assertThat(migration).contains("DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP");
        assertThat(migration).doesNotContain("GENERATED BY DEFAULT AS IDENTITY");
    }
}
