CREATE TABLE IF NOT EXISTS t_hwk_submission (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    homework_id BIGINT NOT NULL,
    student_id BIGINT NOT NULL,
    submit_type VARCHAR(20) NOT NULL,
    answer_text TEXT NULL,
    answer_json TEXT NULL,
    file_url TEXT NULL,
    language VARCHAR(32) NULL,
    submit_status VARCHAR(20) NOT NULL DEFAULT 'SUBMITTED',
    evaluation_status VARCHAR(32) NOT NULL DEFAULT 'NONE',
    review_status VARCHAR(32) NOT NULL DEFAULT 'UNREVIEWED',
    auto_score DECIMAL(6,2) NULL,
    manual_score DECIMAL(6,2) NULL,
    final_score DECIMAL(6,2) NULL,
    comment TEXT NULL,
    version INT NOT NULL DEFAULT 1,
    is_final TINYINT(1) NOT NULL DEFAULT 1,
    submitted_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    reviewed_by BIGINT NULL,
    reviewed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    KEY idx_hwk_submission_homework (homework_id),
    KEY idx_hwk_submission_student (student_id),
    KEY idx_hwk_submission_status (submit_status),
    KEY idx_hwk_submission_evaluation (evaluation_status),
    KEY idx_hwk_submission_review (review_status),
    KEY idx_hwk_submission_submitted_at (submitted_at),
    UNIQUE KEY uk_hwk_submission_version (homework_id, student_id, version),
    CONSTRAINT fk_hwk_submission_homework
        FOREIGN KEY (homework_id) REFERENCES t_hwk_homework(id) ON DELETE CASCADE
);
