CREATE TABLE IF NOT EXISTS crs_resource (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    course_id BIGINT NOT NULL,
    chapter_id BIGINT NULL,
    resource_name VARCHAR(255) NOT NULL,
    resource_type TINYINT NOT NULL DEFAULT 1,
    file_path VARCHAR(500) NULL,
    file_size BIGINT NULL,
    file_format VARCHAR(32) NULL,
    version INT NOT NULL DEFAULT 1,
    external_url VARCHAR(500) NULL,
    access_level VARCHAR(32) NOT NULL DEFAULT 'COURSE',
    download_count INT NOT NULL DEFAULT 0,
    upload_user_id BIGINT NULL,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_crs_resource_course (course_id),
    KEY idx_crs_resource_chapter (chapter_id),
    KEY idx_crs_resource_deleted (is_deleted)
);

CREATE TABLE IF NOT EXISTS t_hwk_homework (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    course_id BIGINT NOT NULL,
    chapter_id BIGINT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NULL,
    type VARCHAR(32) NOT NULL DEFAULT 'FILE',
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    total_score DECIMAL(6, 2) NOT NULL DEFAULT 100.00,
    deadline DATETIME NULL,
    allow_resubmit TINYINT(1) NOT NULL DEFAULT 0,
    allow_late_submit TINYINT(1) NOT NULL DEFAULT 0,
    show_evaluation_before_publish TINYINT(1) NOT NULL DEFAULT 0,
    judge_config_id BIGINT NULL,
    created_by BIGINT NOT NULL,
    published_at DATETIME NULL,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    KEY idx_hwk_homework_course (course_id),
    KEY idx_hwk_homework_status (status),
    KEY idx_hwk_homework_deadline (deadline),
    KEY idx_hwk_homework_deleted (is_deleted)
);
