CREATE TABLE IF NOT EXISTS crs_course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(100) NOT NULL,
    description CLOB,
    teacher_id BIGINT NOT NULL,
    semester VARCHAR(64),
    category VARCHAR(64),
    cover_url VARCHAR(500),
    enrollment_mode VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    invite_code VARCHAR(64),
    max_students INT,
    start_date DATE,
    end_date DATE,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crs_course_teacher ON crs_course (teacher_id);
CREATE INDEX IF NOT EXISTS idx_crs_course_status ON crs_course (status);
CREATE INDEX IF NOT EXISTS idx_crs_course_name ON crs_course (course_name);

CREATE TABLE IF NOT EXISTS crs_course_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    join_method VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    join_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    apply_reason VARCHAR(500),
    approved_by BIGINT,
    joined_at TIMESTAMP,
    left_at TIMESTAMP,
    last_access_at TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_crs_course_member UNIQUE (course_id, user_id),
    CONSTRAINT fk_crs_member_course FOREIGN KEY (course_id) REFERENCES crs_course (id)
);

CREATE INDEX IF NOT EXISTS idx_crs_member_course ON crs_course_member (course_id);
CREATE INDEX IF NOT EXISTS idx_crs_member_user ON crs_course_member (user_id);
CREATE INDEX IF NOT EXISTS idx_crs_member_role_status ON crs_course_member (role, join_status);
