CREATE TABLE IF NOT EXISTS t_auth_user (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL UNIQUE,
    user_type VARCHAR(32) NOT NULL,
    display_name VARCHAR(64) NOT NULL,
    phone VARCHAR(32),
    email VARCHAR(128),
    avatar_url VARCHAR(255),
    password_hash VARCHAR(255) NOT NULL,
    password_salt VARCHAR(128),
    account_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    failed_login_count INT NOT NULL DEFAULT 0,
    locked_until TIMESTAMP,
    last_login_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_auth_user_type ON t_auth_user (user_type);
CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_user_phone ON t_auth_user (phone);
CREATE UNIQUE INDEX IF NOT EXISTS uq_auth_user_email ON t_auth_user (email);
CREATE INDEX IF NOT EXISTS idx_auth_user_status ON t_auth_user (account_status);

CREATE TABLE IF NOT EXISTS t_auth_role (
    role_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_code VARCHAR(64) NOT NULL UNIQUE,
    role_name VARCHAR(64) NOT NULL,
    description VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_auth_role_enabled ON t_auth_role (enabled);

CREATE TABLE IF NOT EXISTS t_auth_permission (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    permission_code VARCHAR(128) NOT NULL UNIQUE,
    permission_name VARCHAR(128) NOT NULL,
    permission_type VARCHAR(32) NOT NULL,
    module_code VARCHAR(32) NOT NULL,
    resource_pattern VARCHAR(255),
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX IF NOT EXISTS idx_auth_permission_type ON t_auth_permission (permission_type);
CREATE INDEX IF NOT EXISTS idx_auth_permission_module ON t_auth_permission (module_code);

CREATE TABLE IF NOT EXISTS t_auth_user_role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    assigned_by BIGINT,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_auth_user_role UNIQUE (user_id, role_id),
    CONSTRAINT fk_auth_user_role_user FOREIGN KEY (user_id) REFERENCES t_auth_user (user_id),
    CONSTRAINT fk_auth_user_role_role FOREIGN KEY (role_id) REFERENCES t_auth_role (role_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_user_role_user ON t_auth_user_role (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_role_role ON t_auth_user_role (role_id);

CREATE TABLE IF NOT EXISTS t_auth_role_permission (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    assigned_by BIGINT,
    assigned_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_auth_role_permission UNIQUE (role_id, permission_id),
    CONSTRAINT fk_auth_role_permission_role FOREIGN KEY (role_id) REFERENCES t_auth_role (role_id),
    CONSTRAINT fk_auth_role_permission_permission FOREIGN KEY (permission_id) REFERENCES t_auth_permission (permission_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_role_permission_role ON t_auth_role_permission (role_id);
CREATE INDEX IF NOT EXISTS idx_auth_role_permission_permission ON t_auth_role_permission (permission_id);

CREATE TABLE IF NOT EXISTS t_auth_session (
    session_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    token_id VARCHAR(128) NOT NULL UNIQUE,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP,
    client_ip VARCHAR(64),
    user_agent VARCHAR(255),
    status VARCHAR(32) NOT NULL DEFAULT 'VALID',
    CONSTRAINT fk_auth_session_user FOREIGN KEY (user_id) REFERENCES t_auth_user (user_id)
);

CREATE INDEX IF NOT EXISTS idx_auth_session_user ON t_auth_session (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_session_expires ON t_auth_session (expires_at);
CREATE INDEX IF NOT EXISTS idx_auth_session_status ON t_auth_session (status);

CREATE TABLE IF NOT EXISTS t_auth_audit_log (
    log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_id BIGINT,
    operation_type VARCHAR(64) NOT NULL,
    target_type VARCHAR(64),
    target_id VARCHAR(64),
    result_status VARCHAR(32) NOT NULL,
    failure_reason VARCHAR(255),
    client_ip VARCHAR(64),
    user_agent VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_auth_audit_operator ON t_auth_audit_log (operator_id);
CREATE INDEX IF NOT EXISTS idx_auth_audit_operation ON t_auth_audit_log (operation_type);
CREATE INDEX IF NOT EXISTS idx_auth_audit_result ON t_auth_audit_log (result_status);
CREATE INDEX IF NOT EXISTS idx_auth_audit_created ON t_auth_audit_log (created_at);

CREATE TABLE IF NOT EXISTS crs_course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(100) NOT NULL,
    description CLOB,
    teacher_id BIGINT NOT NULL,
    semester VARCHAR(64),
    category VARCHAR(64),
    cover_url VARCHAR(500),
    enrollment_mode VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    invite_code VARCHAR(64),
    max_students INT,
    start_date DATE,
    end_date DATE,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crs_course_teacher ON crs_course (teacher_id);
CREATE INDEX IF NOT EXISTS idx_crs_course_status ON crs_course (status);
CREATE INDEX IF NOT EXISTS idx_crs_course_name ON crs_course (course_name);

CREATE TABLE IF NOT EXISTS crs_course_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    join_method VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    join_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    apply_reason VARCHAR(500),
    approved_by BIGINT,
    joined_at TIMESTAMP,
    left_at TIMESTAMP,
    last_access_at TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_crs_course_member UNIQUE (course_id, user_id),
    CONSTRAINT fk_crs_member_course FOREIGN KEY (course_id) REFERENCES crs_course (id)
);

CREATE INDEX IF NOT EXISTS idx_crs_member_course ON crs_course_member (course_id);
CREATE INDEX IF NOT EXISTS idx_crs_member_user ON crs_course_member (user_id);
CREATE INDEX IF NOT EXISTS idx_crs_member_role_status ON crs_course_member (role, join_status);

CREATE TABLE IF NOT EXISTS crs_chapter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    parent_id BIGINT,
    chapter_name VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    objective CLOB,
    visible_status TINYINT NOT NULL DEFAULT 1,
    chapter_type TINYINT NOT NULL DEFAULT 1,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crs_chapter_course FOREIGN KEY (course_id) REFERENCES crs_course (id),
    CONSTRAINT fk_crs_chapter_parent FOREIGN KEY (parent_id) REFERENCES crs_chapter (id)
);

ALTER TABLE crs_chapter ADD COLUMN IF NOT EXISTS chapter_name VARCHAR(255) DEFAULT '';
ALTER TABLE crs_chapter ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE crs_chapter ADD COLUMN IF NOT EXISTS objective CLOB;
ALTER TABLE crs_chapter ADD COLUMN IF NOT EXISTS visible_status TINYINT NOT NULL DEFAULT 1;
ALTER TABLE crs_chapter ADD COLUMN IF NOT EXISTS chapter_type TINYINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS idx_crs_chapter_course_parent_order ON crs_chapter (course_id, parent_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_crs_chapter_course_parent_sort ON crs_chapter (course_id, parent_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_crs_chapter_parent ON crs_chapter (parent_id);

CREATE TABLE IF NOT EXISTS crs_resource (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    chapter_id BIGINT,
    resource_name VARCHAR(255) NOT NULL,
    resource_type VARCHAR(32) NOT NULL,
    visibility VARCHAR(32) NOT NULL DEFAULT 'STUDENT',
    publish_at TIMESTAMP,
    storage_key VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(128) NOT NULL,
    file_size BIGINT NOT NULL DEFAULT 0,
    upload_user_id BIGINT NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crs_resource_course FOREIGN KEY (course_id) REFERENCES crs_course (id),
    CONSTRAINT fk_crs_resource_chapter FOREIGN KEY (chapter_id) REFERENCES crs_chapter (id)
);

CREATE INDEX IF NOT EXISTS idx_crs_resource_course ON crs_resource (course_id);
CREATE INDEX IF NOT EXISTS idx_crs_resource_chapter ON crs_resource (chapter_id);
CREATE INDEX IF NOT EXISTS idx_crs_resource_uploader ON crs_resource (upload_user_id);
