CREATE TABLE IF NOT EXISTS crs_course (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_name VARCHAR(100) NOT NULL,
    description CLOB,
    teacher_id BIGINT NOT NULL,
    semester VARCHAR(64),
    category VARCHAR(64),
    cover_url VARCHAR(500),
    enrollment_mode VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    invite_code VARCHAR(64),
    max_students INT,
    start_date DATE,
    end_date DATE,
    status VARCHAR(32) NOT NULL DEFAULT 'DRAFT',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_crs_course_teacher ON crs_course (teacher_id);
CREATE INDEX IF NOT EXISTS idx_crs_course_status ON crs_course (status);
CREATE INDEX IF NOT EXISTS idx_crs_course_name ON crs_course (course_name);

CREATE TABLE IF NOT EXISTS crs_course_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    role VARCHAR(32) NOT NULL,
    join_method VARCHAR(32) NOT NULL DEFAULT 'CREATED',
    join_status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    apply_reason VARCHAR(500),
    approved_by BIGINT,
    joined_at TIMESTAMP,
    left_at TIMESTAMP,
    last_access_at TIMESTAMP,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_crs_course_member UNIQUE (course_id, user_id),
    CONSTRAINT fk_crs_member_course FOREIGN KEY (course_id) REFERENCES crs_course (id)
);

CREATE INDEX IF NOT EXISTS idx_crs_member_course ON crs_course_member (course_id);
CREATE INDEX IF NOT EXISTS idx_crs_member_user ON crs_course_member (user_id);
CREATE INDEX IF NOT EXISTS idx_crs_member_role_status ON crs_course_member (role, join_status);

CREATE TABLE IF NOT EXISTS crs_chapter (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id BIGINT NOT NULL,
    parent_id BIGINT,
    chapter_name VARCHAR(255) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    objective CLOB,
    visible_status TINYINT NOT NULL DEFAULT 1,
    chapter_type TINYINT NOT NULL DEFAULT 1,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_crs_chapter_course FOREIGN KEY (course_id) REFERENCES crs_course (id),
    CONSTRAINT fk_crs_chapter_parent FOREIGN KEY (parent_id) REFERENCES crs_chapter (id)
);

ALTER TABLE crs_chapter ADD COLUMN IF NOT EXISTS chapter_name VARCHAR(255) DEFAULT '';
ALTER TABLE crs_chapter ADD COLUMN IF NOT EXISTS sort_order INT NOT NULL DEFAULT 0;
ALTER TABLE crs_chapter ADD COLUMN IF NOT EXISTS objective CLOB;
ALTER TABLE crs_chapter ADD COLUMN IF NOT EXISTS visible_status TINYINT NOT NULL DEFAULT 1;
ALTER TABLE crs_chapter ADD COLUMN IF NOT EXISTS chapter_type TINYINT NOT NULL DEFAULT 1;
CREATE INDEX IF NOT EXISTS idx_crs_chapter_course_parent_order ON crs_chapter (course_id, parent_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_crs_chapter_course_parent_sort ON crs_chapter (course_id, parent_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_crs_chapter_parent ON crs_chapter (parent_id);
